// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  education: dynamic(() => import("./Education")),
  hero: dynamic(() => import("./Hero")),
  tech_list: dynamic(() => import("./TechList")),
  text_links: dynamic(() => import("./TextLinks")),
};
